<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net48</TargetFrameworks>
		<LangVersion>14.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\SanteDB.licenseheader" Link="SanteDB.licenseheader" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NUnit" Version="[4.5.0,5)" />
    <PackageReference Include="NUnit3TestAdapter" Version="[6.1.0,7)" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="[18.3.0,18.4)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SanteDB.Security.Certs.BouncyCastle\SanteDB.Security.Certs.BouncyCastle.csproj" />
  </ItemGroup>

</Project>
